#!/bin/sh

g++ -Dsingle_threaded -I../../inc\
    ../../src/heaps.cpp\
    ../../src/processes.cpp\
    ../../src/executors.cpp\
    ../../src/reader.cpp\
    ../../src/symbols.cpp\
    ../../src/types.cpp\
    ../../src/globals.cpp\
    test1.cpp -o test1
