#!/bin/sh

g++ -g -Dsingle_threaded -I../../inc\
	../../src/reader.cpp\
	../../src/executors.cpp\
	../../src/heaps.cpp\
	../../src/symbols.cpp\
	../../src/symtable.cpp\
	../../src/types.cpp\
	../../src/processes.cpp\
	../../src/globals.cpp\
	run_bytecode.cpp\
	-o run_bytecode -pthread
