#! /usr/bin/awk -f

# This file is used by "collate" to process the crumbs line of
# the sources.

BEGIN {OFS = ""; ORS = "";}

{
	len = split($0, fields);
	# awk is 1-based
	for(i = 1; i <= len; i = i + 1) {
		print "&raquo; <a href='",fields[i],".html'>",fields[i],"</a> ";
	}
}

